-- =========================================================================================================
-- DAY 04 : Advanced SQL Aggregation & Analysis
-- Database : sql_learning (pgAdmin)
-- Dataset  : Retail Sales Dataset(https://www.kaggle.com/datasets/mohammadtalib786/retail-sales-dataset)
-- =========================================================================================================


--============================================================
--1. CASE WHEN
--CASE WHEN allows us to apply conditions inside a SQL query.
--It works like an IF–ELSE statement
--============================================================

-- For every transaction,If the amount is at least 1000,it displays High Value Otherwise, it displays Regular.

SELECT
    transaction_id,
    total_amount,
    CASE
        WHEN total_amount >= 1000 THEN 'High Value'
        ELSE 'Regular'
    END AS sale_type
FROM retail_sales;

--Multiple Conditions

SELECT
    transaction_id,
    total_amount,
    CASE
        WHEN total_amount >= 1500 THEN 'High'     --checks the conditions from top to bottom
        WHEN total_amount >= 500 THEN 'Medium'
        ELSE 'Low'
    END AS sale_category
FROM retail_sales;

--========================================
--2. Conditional Counting
--========================================

-- Retrieving count of how many transactions are high-value.

SELECT
    COUNT(
        CASE
            WHEN total_amount >= 1000 THEN 1
        END
    ) AS high_value_transactions
FROM retail_sales;

-- Anothr approach

SELECT
    SUM(
        CASE
            WHEN total_amount >= 1000 THEN 1
            ELSE 0
        END
    ) AS high_value_transactions
FROM retail_sales;

--=================================
--3. Multiple Results in One Query
--=================================

-- Retrieving several counts in one query

SELECT
    COUNT(*) AS total_transactions,
    SUM(
        CASE
            WHEN total_amount >= 1000 THEN 1
            ELSE 0
        END
    ) AS high_value_transactions,
    SUM(
        CASE
            WHEN total_amount < 1000 THEN 1
            ELSE 0
        END
    ) AS regular_transactions
FROM retail_sales;

--=====================================
--4. Conditional SUM
--=====================================

-- Retrieving revenue generated by male and female customers in one result


SELECT
    SUM(
        CASE
            WHEN gender = 'Male' THEN total_amount
            ELSE 0
        END
    ) AS male_revenue,
    SUM(
        CASE
            WHEN gender = 'Female' THEN total_amount
            ELSE 0
        END
    ) AS female_revenue
FROM retail_sales;

--=========================================
--5. Conditional Aggregation with GROUP BY
--=========================================

--Retriveing number of male and female customers in every category

SELECT
    product_category,
    SUM(
        CASE
            WHEN gender = 'Male' THEN 1
            ELSE 0
        END
    ) AS male_transactions,
    SUM(
        CASE
            WHEN gender = 'Female' THEN 1
            ELSE 0
        END
    ) AS female_transactions
FROM retail_sales
GROUP BY product_category;

--===========================================
--6. Calculating Percentages
--Part ÷ Total × 100
--===========================================

-- Retriveing percentage of high-value transactions

SELECT
    ROUND(
        100.0 *                                      --Using 100.0 helps PostgreSQL perform decimal division
        SUM(
            CASE
                WHEN total_amount >= 1000 THEN 1
                ELSE 0
            END
        )
        / COUNT(*),
        2
    ) AS high_value_percentage
FROM retail_sales;

--=================================================
--7. Category Percentage
--=================================================

--Retriveing percentage of all transactions belongs to each category

SELECT
    product_category,
    COUNT(*) AS category_transactions,
    ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM retail_sales),
        2
    ) AS transaction_percentage
FROM retail_sales
GROUP BY product_category
ORDER BY transaction_percentage DESC;

--=======================================
--8. NULLIF()
--=======================================

--NULLIF(quantity, 0) means : If quantity is zero, return NULL. Otherwise, return quantity

SELECT
    total_amount /
    NULLIF(quantity, 0)    -- prevents dividing by zero error
FROM retail_sales;  

--======================================================
--9. COALESCE()
--COALESCE() replaces a NULL value with another value
--======================================================

SELECT
    transaction_id,
    COALESCE(age, 0) AS customer_age    --If age is missing,displays 0
FROM retail_sales;

--If no matching records exist, COALESCE() displays 0 instead of NULL

SELECT
    COALESCE(SUM(total_amount), 0) AS total_revenue
FROM retail_sales
WHERE product_category = 'Furniture';

---=================================================================
--10. Weighted Average
--A normal average treats every row equally
--==================================================================

--Sum of price × quantity/Sum of quantity

SELECT
    ROUND(
        SUM(price_per_unit * quantity) /
        NULLIF(SUM(quantity), 0),
        2
    ) AS weighted_average_price
FROM retail_sales;

--=============================================
--11.Extract
--=============================================

--sale_date column stores the transaction date
-- Displaying the year


SELECT
    sale_date,
    EXTRACT(YEAR FROM sale_date) AS sale_year
FROM retail_sales;

--Display the month number

 SELECT
    sale_date,
    EXTRACT(MONTH FROM sale_date) AS sale_month
FROM retail_sales;

--Display the month name (TO_CHAR)

SELECT
    sale_date,
    TO_CHAR(sale_date, 'Month') AS month_name
FROM retail_sales;

--Monthly Revenue

SELECT
    TO_CHAR(sale_date, 'YYYY-MM') AS sale_month,
    SUM(total_amount) AS monthly_revenue
FROM retail_sales
GROUP BY TO_CHAR(sale_date, 'YYYY-MM')
ORDER BY sale_month;

--====================================
--Monthly Transaction Report
--====================================

SELECT
    TO_CHAR(sale_date, 'YYYY-MM') AS sale_month,
    COUNT(*) AS transaction_count,
    SUM(quantity) AS units_sold,
    SUM(total_amount) AS total_revenue,
    ROUND(AVG(total_amount), 2) AS average_transaction
FROM retail_sales
GROUP BY TO_CHAR(sale_date, 'YYYY-MM')
ORDER BY sale_month;

--Retrieving total transactions and high-value transactions for every month

SELECT
    TO_CHAR(sale_date, 'YYYY-MM') AS sale_month,
    COUNT(*) AS total_transactions,
    SUM(
        CASE
            WHEN total_amount >= 1000 THEN 1
            ELSE 0
        END
    ) AS high_value_transactions,
    SUM(total_amount) AS total_revenue
FROM retail_sales
GROUP BY TO_CHAR(sale_date, 'YYYY-MM')
ORDER BY sale_month;

--==============================================================
--Complete Practical Example
--Create a category-level report containing:
--Total transactions
--Male transactions
--Female transactions
--Total quantity
--Total revenue
--Average sale
--Percentage of all transactions
--==============================================================

SELECT
    product_category,
    COUNT(*) AS total_transactions,
    SUM(
        CASE
            WHEN gender = 'Male' THEN 1
            ELSE 0
        END
    ) AS male_transactions,
    SUM(
        CASE
            WHEN gender = 'Female' THEN 1
            ELSE 0
        END
    ) AS female_transactions,
    SUM(quantity) AS total_quantity,
    SUM(total_amount) AS total_revenue,
    ROUND(AVG(total_amount), 2) AS average_sale,
    ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM retail_sales),
        2
    ) AS transaction_percentage
FROM retail_sales
GROUP BY product_category
ORDER BY total_revenue DESC;





