--=========================================================================================
--Question 9: Rank Products Inside Each Category
--First calculate the total revenue generated by each product
--Then rank products from highest to lowest revenue inside their respective categories
--Display: Product category, Product name, Total revenue, Revenue rank
--=========================================================================================

WITH Product_Details AS (
SELECT product_category,
       product_name,
       SUM(total_revenue) AS total_revenue,
       DENSE_RANK()OVER( PARTITION BY product_category
                        ORDER BY SUM(total_revenue) DESC) AS revenue_rank
FROM online_sales
GROUP BY product_name,product_category
)
SELECT * FROM Product_Details;

--============================================================================
-- Concepts Covered
-- CTE           -> Creates a temporary named result set
-- GROUP BY      -> Groups rows by product category and product name
-- SUM()         -> Calculates total revenue for each product
-- DENSE_RANK()  -> Ranks products without skipping rank numbers
-- OVER()        -> Defines the window for the window function
-- PARTITION BY  -> Restarts ranking within each product category
-- ORDER BY      -> Orders products by total revenue from highest to lowest
--=============================================================================


  
